import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  // variable: "--font-poppins",
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "700"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
